### ISSUE TITLE
crash on large dataset

### ISSUE THREAD

**Issue by lhaclove** [IGBB/PAST#35]
I got about 770k snps and a LD files with 38811k lines (from tassel5 ), PAST used about 1 Tb mermory  and the cluster stoped R process, and the %dopar% not make faster on cluster and used more mermory than %do%.

**Comment by adamthrash** [comment]
We've recently discovered this bug as well. I believe I know where the problem is, and I'm testing a fix today. I'll keep this issue updates. Thanks for the feedback!

**Comment by adamthrash** [comment]
Hi @lhaclove, please try building and installing PAST from [this branch](https://github.com/IGBB/PAST/tree/memory_issue). The changes in this branch allow me to run a large dataset on my desktop, which I cannot do without these chances.

**Comment by lhaclove** [comment]
New code works fine!
