### ISSUE TITLE
Using PAST for human data

### ISSUE THREAD

**Issue by prihoda** [IGBB/PAST#42]
Hi @adamthrash, can you give me an example on using PAST for human GWAS data? Is there some documentation available on how to collect the various inputs in proper format?

**Comment by adamthrash** [comment]
Hi @prihoda,

Example input data can be found [here](https://github.com/IGBB/PAST/tree/master/inst/extdata). So long as your GWAS data is formatted like the association and effects file, you should be able to use it with PAST.
