### ISSUE TITLE
error in load_GWAS_data

### ISSUE THREAD

**Issue by xiahui625649** [IGBB/PAST#44]
gwas_data <- load_GWAS_data(demo_association_file, demo_effects_file)
error: Problem with `mutate()` input `..1`.
i `..1 = .data`.
x `..1` must be a vector, not a `rlang_data_pronoun` object.
Run `rlang::last_error()` to see where the error occurred.

**Comment by adamthrash** [comment]
Can you provide the full script where you ran this code?

**Comment by xiahui625649** [comment]
I just run the example in the package. My R version is R 3.6.0, is it the reason?

`demo_association_file = system.file("extdata", "association.txt.xz",package = "PAST", mustWork = TRUE)
demo_effects_file = system.file("extdata", "effects.txt.xz",package = "PAST", mustWork = TRUE)
gwas_data <- load_GWAS_data(demo_association_file, demo_effects_file)`

> error: Problem with mutate() input ..1.
i ..1 = .data.
x ..1 must be a vector, not a rlang_data_pronoun object.
Run rlang::last_error() to see where the error occurred

**Comment by adamthrash** [comment]
Possibly. The latest version of PAST requires R 4.0 or greater. Can you upgrade to R 4.0 and try running the example?

**Comment by adamthrash** [comment]
Closed due to lack of response.
